### ISSUE TITLE
Plot pool and mainnet data points

### ISSUE THREAD

**Issue by leviable** [Noso-Project/explorer.nosocoin.com#6]
It would be neat if the explorer could display interesting charts to the user, such as:

* Pool hash rate over time
* Pool miner count over time
* Network difficulty over time

Probably several others. Most of that info is already there, just needs to be aggregated and displayed. Would that be difficult?

**Comment by gonefishing4422** [comment]
Sorry, old request pertaining to pools no longer applicable. Closing.
