### ISSUE TITLE
The search bar goes to Order Look Up when inputted an alias with or without the prefix "A-"

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/explorer.nosocoin.com#7]
Hey @gonefishing4422,

Looks like something is wrong and the search bar code that should distinguish from an order or an alias is not working properly.

Just thought I should give'ya the heads up.

Cheers,
Gus

**Comment by gonefishing4422** [comment]
Thanks. Old issue that was resolved.  Closing

**Comment by gcarreno** [comment]
Hey @gonefishing4422,

Nope, still there!!

I completely invalidated my cache of the site, entered `A-gcarreno-main` on the search box and this is what I got:

![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/448c418b-9c6c-4f62-bfb7-7269a0e503b2)

Could it be one of these things:
- I'm using Firefox
- My alias has an hyphen

Apart from that, the fact that for just a brief moment there are 2 edit boxes is a tad suspicious, right?

Cheers,
Gus
