### ISSUE TITLE
If the alias contains an hyphen, it is redirected to the orders, not the account info

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/explorer.nosocoin.com#8]
Hey @gonefishing4422,

Looks like I was right to mention the hyphen before:

![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/5f034377-24d1-4126-9944-e8c71569498d)

If you put an alias that does not have an hyphen, it works as intended.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @gonefishing4422,

On this line: 
[} else if (/^A-[a-zA-Z0-9]{1,31}$/.test(input)) {](https://github.com/Noso-Project/explorer.nosocoin.com/blob/04f373a3314dcf6e6b022f1a4d295ca4fdcc2f61/qr.html#L187)

it should read:
```js
} else if (/^A-[a-zA-Z0-9\-]{1,31}$/.test(input)) {
```

This should fix the problem with the hyphen, but it still leaves a ton of other possible characters.

With "^A-[a-zA-Z0-9]{1,31}$", no match:
![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/90803705-b6b9-41e7-8edd-2cd35358bd92)

With "^A-[a-zA-Z0-9\-]{1,31}$", 1 match:
![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/b52db9ba-6718-46fa-96da-9d9dc5a12f93)

But it should really be "^A-.*$", so you can match anything:
![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/2237f149-1924-4c21-96ae-2c0071ba76be)


Cheers,
Gus

**Comment by gonefishing4422** [comment]
Resolved
