### ISSUE TITLE
[Proposal] Slightly improved regexp for alias

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/explorer.nosocoin.com#9]
Hey @gonefishing4422,

After a bit more thought, and because not everyone will respect the capital `A` from the hint, I propose you change the regexp to: `/^[aA]-.*&/`.

![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/0d35cbbe-11be-4447-b460-328c16463953)

![image](https://github.com/Noso-Project/explorer.nosocoin.com/assets/81799/f8294135-c806-4fe7-88f3-e5a08fa332b0)

Cheers,
Gus

**Comment by gonefishing4422** [comment]
Updated to this:

/^[aA]-.*$/.

Thanks ..
